import datetime
from xml.sax.saxutils import escape
from zipfile import ZipFile, ZIP_DEFLATED


W_NAMESPACE = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
REL_NAMESPACE = "http://schemas.openxmlformats.org/package/2006/relationships"
OPC_RELATIONSHIPS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
OPC_CORE_PROPS = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties"
OPC_EXT_PROPS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties"


def paragraph_xml(text: str, size_pt: int = 14, bold: bool = False, align: str | None = None) -> str:
    size_val = str(int(size_pt * 2))  # half-points in WordprocessingML
    text_escaped = escape(text)
    jc_xml = f"<w:pPr><w:jc w:val=\"{align}\"/></w:pPr>" if align else ""
    b_xml = "<w:b/>" if bold else ""
    return (
        f"<w:p>{jc_xml}"
        f"<w:r><w:rPr>"
        f"<w:rFonts w:ascii=\"Times New Roman\" w:hAnsi=\"Times New Roman\" w:eastAsia=\"Times New Roman\" w:cs=\"Times New Roman\"/>"
        f"<w:sz w:val=\"{size_val}\"/><w:szCs w:val=\"{size_val}\"/>{b_xml}"
        f"</w:rPr><w:t>{text_escaped}</w:t></w:r>"
        f"</w:p>"
    )


def build_document_xml(paragraphs: list[str]) -> str:
    body_content = "".join(paragraphs) + (
        "<w:sectPr>"
        "<w:pgSz w:w=\"12240\" w:h=\"15840\"/>"  # A4 size in twips
        "<w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\" w:header=\"708\" w:footer=\"708\" w:gutter=\"0\"/>"
        "</w:sectPr>"
    )
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        f"<w:document xmlns:w=\"{W_NAMESPACE}\">"
        f"<w:body>{body_content}</w:body>"
        "</w:document>"
    )


def build_content_types_xml() -> str:
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">"
        "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>"
        "<Default Extension=\"xml\" ContentType=\"application/xml\"/>"
        "<Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/>"
        "<Override PartName=\"/word/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml\"/>"
        "<Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/>"
        "<Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/>"
        "</Types>"
    )


def build_root_rels_xml() -> str:
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        f"<Relationships xmlns=\"{REL_NAMESPACE}\">"
        f"<Relationship Id=\"rId1\" Type=\"{OPC_RELATIONSHIPS}\" Target=\"word/document.xml\"/>"
        f"<Relationship Id=\"rId2\" Type=\"{OPC_CORE_PROPS}\" Target=\"docProps/core.xml\"/>"
        f"<Relationship Id=\"rId3\" Type=\"{OPC_EXT_PROPS}\" Target=\"docProps/app.xml\"/>"
        "</Relationships>"
    )


def build_styles_xml() -> str:
    # Minimal styles; font/size are enforced by per-run rPr
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        f"<w:styles xmlns:w=\"{W_NAMESPACE}\"><w:docDefaults>"
        "<w:rPrDefault><w:rPr>"
        "<w:rFonts w:ascii=\"Times New Roman\" w:hAnsi=\"Times New Roman\" w:eastAsia=\"Times New Roman\" w:cs=\"Times New Roman\"/>"
        "<w:sz w:val=\"28\"/><w:szCs w:val=\"28\"/>"
        "</w:rPr></w:rPrDefault>"
        "<w:pPrDefault><w:pPr/></w:pPrDefault>"
        "</w:docDefaults></w:styles>"
    )


def build_core_xml() -> str:
    now = datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" "
        "xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" "
        "xmlns:dcmitype=\"http://purl.org/dc/dcmitype/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">"
        "<dc:title>Database Assignment 3</dc:title>"
        "<dc:subject>Database Summer Semester</dc:subject>"
        "<dc:creator>Generated by Script</dc:creator>"
        f"<dcterms:created xsi:type=\"dcterms:W3CDTF\">{now}</dcterms:created>"
        f"<dcterms:modified xsi:type=\"dcterms:W3CDTF\">{now}</dcterms:modified>"
        "</cp:coreProperties>"
    )


def build_app_xml() -> str:
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\" "
        "xmlns:vt=\"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes\">"
        "<Application>Python</Application>"
        "<DocSecurity>0</DocSecurity>"
        "<ScaleCrop>false</ScaleCrop>"
        "<Company></Company>"
        "<LinksUpToDate>false</LinksUpToDate>"
        "<SharedDoc>false</SharedDoc>"
        "<HyperlinksChanged>false</HyperlinksChanged>"
        "<AppVersion>16.0000</AppVersion>"
        "</Properties>"
    )


def generate_docx(output_path: str) -> None:
    paragraphs: list[str] = []

    # Header
    paragraphs.append(paragraph_xml("University of Engineering & Technology Peshawar", size_pt=16, bold=True, align="center"))
    paragraphs.append(paragraph_xml("Department of Computer Science & IT", size_pt=14))
    paragraphs.append(paragraph_xml("Subject: Database Summer Semester", size_pt=14))
    paragraphs.append(paragraph_xml("Total Marks : 10", size_pt=14))
    paragraphs.append(paragraph_xml("Assignment No 3", size_pt=14))
    paragraphs.append(paragraph_xml("", size_pt=14))

    # Q1
    paragraphs.append(paragraph_xml("Q No 1. Case Study on Query Optimization", size_pt=16, bold=True))
    paragraphs.append(paragraph_xml("A university database has two tables:", size_pt=14))
    paragraphs.append(paragraph_xml("- Student(student_id, name, age, course_id)", size_pt=14))
    paragraphs.append(paragraph_xml("- Course(course_id, course_name)", size_pt=14))
    paragraphs.append(paragraph_xml("Write two different SQL queries to retrieve the names of students enrolled in the course \"Database Systems.\"", size_pt=14))

    paragraphs.append(paragraph_xml("Query 1: Explicit join", size_pt=14, bold=True))
    paragraphs.append(paragraph_xml("SELECT s.name", size_pt=14))
    paragraphs.append(paragraph_xml("FROM Student AS s", size_pt=14))
    paragraphs.append(paragraph_xml("JOIN Course  AS c ON c.course_id = s.course_id", size_pt=14))
    paragraphs.append(paragraph_xml("WHERE c.course_name = 'Database Systems';", size_pt=14))
    paragraphs.append(paragraph_xml("", size_pt=14))

    paragraphs.append(paragraph_xml("Query 2: EXISTS (semi-join)", size_pt=14, bold=True))
    paragraphs.append(paragraph_xml("SELECT s.name", size_pt=14))
    paragraphs.append(paragraph_xml("FROM Student AS s", size_pt=14))
    paragraphs.append(paragraph_xml("WHERE EXISTS (", size_pt=14))
    paragraphs.append(paragraph_xml("  SELECT 1", size_pt=14))
    paragraphs.append(paragraph_xml("  FROM Course AS c", size_pt=14))
    paragraphs.append(paragraph_xml("  WHERE c.course_id = s.course_id", size_pt=14))
    paragraphs.append(paragraph_xml("    AND c.course_name = 'Database Systems'", size_pt=14))
    paragraphs.append(paragraph_xml(");", size_pt=14))
    paragraphs.append(paragraph_xml("", size_pt=14))

    paragraphs.append(paragraph_xml("Optimizer transformations and likely execution plans:", size_pt=14, bold=True))
    paragraphs.append(paragraph_xml("Heuristic (rule-based) optimizations:", size_pt=14))
    paragraphs.append(paragraph_xml("- Push selections: Apply c.course_name = 'Database Systems' early to reduce Course rows.", size_pt=14))
    paragraphs.append(paragraph_xml("- Projection pushdown: Keep only needed columns (s.name, s.course_id, c.course_id, c.course_name).", size_pt=14))
    paragraphs.append(paragraph_xml("- Join reordering/associativity: EXISTS acts as a semi-join; join smaller filtered set first.", size_pt=14))
    paragraphs.append(paragraph_xml("- Replace IN/EXISTS with semi-join where appropriate to avoid duplicates.", size_pt=14))
    paragraphs.append(paragraph_xml("Cost-based choices (statistics and indexes):", size_pt=14))
    paragraphs.append(paragraph_xml("- If indexed on Course(course_name) or (course_name, course_id), first find course_id, then join Student.", size_pt=14))
    paragraphs.append(paragraph_xml("- If indexed on Student(course_id) (ideally covering with (course_id, name)), use index nested-loops to probe Student.", size_pt=14))
    paragraphs.append(paragraph_xml("- Without useful indexes for equality, a hash join (build on filtered Course, probe Student) is common.", size_pt=14))
    paragraphs.append(paragraph_xml("- If both sides are ordered on course_id (e.g., clustered), a merge join can be optimal.", size_pt=14))
    paragraphs.append(paragraph_xml("", size_pt=14))

    # Q2
    paragraphs.append(paragraph_xml("Q No 2. Indexing Analysis", size_pt=16, bold=True))
    paragraphs.append(paragraph_xml("(a) Recommended index for filtering on dept and age simultaneously:", size_pt=14, bold=True))
    paragraphs.append(paragraph_xml("Use a composite B-tree index on (dept, age). This supports equality lookups on dept and efficient range scans or equality on age within each department. Compared to two single-column indexes, the composite index avoids index-merge and yields better locality and fewer page reads. If queries often return only name or a few columns, consider a covering index with included columns.", size_pt=14))
    paragraphs.append(paragraph_xml("(b) Inefficient index type for range queries on salary and why:", size_pt=14, bold=True))
    paragraphs.append(paragraph_xml("A hash index is inefficient (often unusable) for range predicates such as salary BETWEEN a AND b because hashing destroys ordering and prevents ordered scans. B-tree indexes preserve key order and are preferred for range queries.", size_pt=14))
    paragraphs.append(paragraph_xml("", size_pt=14))

    # Q3
    paragraphs.append(paragraph_xml("Q No 3. Join Algorithm Evaluation", size_pt=16, bold=True))
    paragraphs.append(paragraph_xml("You are joining Orders (≈5,000,000 rows) and Customers (≈50,000 rows) on equality (e.g., customer_id).", size_pt=14))
    paragraphs.append(paragraph_xml("- Most efficient generally (unsorted inputs, no selective index): Hash Join. Build hash on smaller Customers (≈50k), then probe with Orders (≈5M). Near linear time; avoids random I/O; memory for a 50k hash is manageable.", size_pt=14))
    paragraphs.append(paragraph_xml("- If there is an index on Orders(customer_id) (ideally clustered/covering), an Index Nested Loops can be competitive: scan Customers (50k) and probe Orders via the index. Best when each customer matches few orders (high selectivity).", size_pt=14))
    paragraphs.append(paragraph_xml("- If both inputs are already sorted on customer_id, a Merge Join can be excellent, streaming both once with minimal memory. Otherwise, sorting 5M rows is expensive.", size_pt=14))
    paragraphs.append(paragraph_xml("Key factors: input sizes (5M vs 50k), available indexes (especially on Orders.customer_id), equality join predicate, and whether data is pre-sorted. In most real scenarios without perfect ordering, Hash Join is the default winner.", size_pt=14))

    document_xml = build_document_xml(paragraphs)

    with ZipFile(output_path, "w", compression=ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", build_content_types_xml())
        zf.writestr("_rels/.rels", build_root_rels_xml())
        zf.writestr("word/document.xml", document_xml)
        zf.writestr("word/styles.xml", build_styles_xml())
        zf.writestr("docProps/core.xml", build_core_xml())
        zf.writestr("docProps/app.xml", build_app_xml())


def main() -> None:
    output_path = "/workspace/Database_Assignment_3.docx"
    generate_docx(output_path)
    print(f"Saved: {output_path}")


if __name__ == "__main__":
    main()

